### ISSUE TITLE
how about renaming this to litmus-probe

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-probe#1]
is more clear imho

**Comment by woodsaj** [comment]
@Dieterbe my concern here is that the probe will be used for more then just Limus data.

ie, we are working on sitespeed integration and though not decided there is a possibly that it will be handled as a separate integration and not part of litmus.  Though it will still run as part of the probe.

**Comment by Dieterbe** [comment]
hmm i thought the sitespeed stuff would fall nicely within the scope of litmus ("website monitoring")
my reasoning was, once we add other integrations (docker/lan/system/.. monitoring) we'd probably have a different daemon for those. although that's up in the air too i guess.

**Comment by woodsaj** [comment]
litmus isnt 'website monitoring'

from my point of view, the relationship between sitespeed and litmus is the same as between host metrics and litmus.  The data is related, but measures different things.

Sitespeed produces 50x more data (cardinality) then all of the current litmus checks combined.
