### ISSUE TITLE
http/s host header should not include the port, when the default port is being used.

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-probe#13]
baidu.com rejects https requests with a host header set to "www.baidu.com:443"

Including the port is not required when using the default port, but it is still valid according to the spec
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

Given that baidu rejects these request, there may also be other web servers that also interpret the spec differently.

**Comment by Dieterbe** [comment]
i find the spec not very clear, but interpret more on the side that it suggests not including the port when it's default. for 2 reasons:

one:

```
The Host request-header field specifies the Internet host and port number of the resource
being requested, as obtained from the original URI given by the user
or referring resource (generally an HTTP URL, as described in section 3.2.2)
```

the original URI provided by the user does not include the `:80` ergo we shouldn't add it.

two:

```
For example, a request on the origin server for <http://www.w3.org/pub/WWW/> would properly include:

       GET /pub/WWW/ HTTP/1.1
       Host: www.w3.org
```

no port included there either.

anyway, i just saw another customer using varnish being impacted by this so i'm happy that we're removing the port now when it is default. also it'll save us some bandwidth :)
