### ISSUE TITLE
gorilla websocket library?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-probe#20]
i couldn't find the previous discussion, but i believe @woodsaj has mentioned that go's websocket library sucks and that's why we still have the nodejs wrapper.

check the comments out in this thread: https://www.reddit.com/r/golang/comments/3l13kh/build_your_own_slack_bot_in_go/?

looks like gorilla's websocket library may fix our problems?

**Comment by woodsaj** [comment]
the current problem with the collector controller is with socketio.  Everyone already knows that the gorilla websocket library is superior, which is why socketio uses it, and so does macaron (the web framework used by grafana).
