### ISSUE TITLE
if port is empty string, use default port for the protocol

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-probe#23]
currently the port to use for http/https/dns is parsed from string to int and the check fails if the parsing fails.

if a port is set to an empty string, "", then the parsing will fail.  We should treat empty strings as implying the default port should be used.

**Comment by Dieterbe** [comment]
shouldn't https port be 443 ?

**Comment by woodsaj** [comment]
thanks dieter.  fixed.
