### ISSUE TITLE
allow overriding host header for http/https checks

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-probe#39]
If a user sets a "host" header in the check "headers" configuration it is not currently honored. 

As documented in https://golang.org/pkg/net/http/#Request, to override the host you need to set request.Host

**Comment by DanCech** [comment]
so something like this should do the needful, I think:
```
		if dummyRequest.Host != "" {
			request.Host = dummyRequest.Host
		}
```

**Comment by woodsaj** [comment]
yep, exactly that.

**Comment by DanCech** [comment]
ok, I'll throw that in the downloadLimit branch

**Comment by woodsaj** [comment]
fixed in https://github.com/raintank/raintank-probe/commit/a2f6ae8aa6cdf798e87899e20654aba81f695b8c
