### ISSUE TITLE
use heka as a base?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-probe#4]
this came up as part of https://github.com/raintank/ops/issues/97
I think it may make sense to use heka as a base platform for the new probe.
why?
- it has in-memory and on-disk buffering built-in (no strong sync() semantics, but still)
- it is very extensible, in case we want to add more plugins later to provide other kinds of metrics
- it has ways to graph data in flight , do thresholding/anomaly detection in realtime as data flows through, etc

cons:
- it comes with overhead, it is a very flexible tool so it does a bunch of stuff we don't need yet or may never need. (like the internal flexible routing system with matchers and protobuf encoding/decoding)
- it uses non-go code, like the lua sandbox which is C, so it's harder to build.

quote @woodsaj 

> I hadn't considered using Heka as the core of the collector process, but it does sound interesting. I would assume that you would use an input plugin for scheduling and executing checks, and an output plugin for sending results. This would mean that we would need 2 connections to the grafana-server. 1 for the input plugin to receive check add/update/delete commands and one for the output plugin to send results. Which would complicate tracking whether a collector is online or not. I would much rather just have one persistent authenticated connection with bi-directional communication.

we wouldn't need 2 connections if both plugins import a separate package that has a connection singleton. (instantiated by only 1 of the plugins, but used by both)

personally I think the in-mem and on-disk buffering alone is not enough to make this a good choice.
we want to keep this lightweight so it runs well on rbpi's. so unless we see a clear need for any of the other features, i say we just write it custom for ourselves, possibly reusing the nsqd diskqueue.go

I like the raintank-metric development model where we keep it simple at first and iterate on it, and once we hit clear roadblocks and need to re-architect things, only then do we make an impactful decision like adopting a tool like heka, porting the code is usually not too much work.

**Comment by woodsaj** [comment]
I do see something like Heka as a foundation of the collector being useful long term as we add in additional capabilites.  This would be very useful as the collector transitions in to an agent like tool that can run on customer servers to ingest data.  For example, we could add a carbon listener plugin that then ships the metrics back to us. Or a Statsd listener. And the community could add input plugins to collect data from a range of sources.

**Comment by woodsaj** [comment]
future plan is to use Snap.
