### ISSUE TITLE
Mistake in README.md

### ISSUE THREAD

**Issue by FireHelmet** [raintank/raintank-probe#45]
Hello,

In the part : b.) (For CentOS, so RPM package manager)

It's:

add PackageCloud to repo.
curl -s https://packagecloud.io/install/repositories/raintank/raintank/script.rpm.sh | sudo bash
Install raintank-probe package
yum install raintank-probe

not:

![image](https://user-images.githubusercontent.com/17533298/27025190-e523d684-4f59-11e7-9185-f875e60d9a01.png)

**Comment by woodsaj** [comment]
Thanks @FireHelmet
