### ISSUE TITLE
Problem running raintank-probe on Raspbian

### ISSUE THREAD

**Issue by mmarin11** [raintank/raintank-probe#57]
Dear community

Im trying ro tun raintank-probe in Raspberry Pi running rasbian  but when trying to run the daemon I get the following error

pi@elp-us:~/go $ sudo /root/go/bin/raintank-probe
sudo: unable to resolve host elp-us
2018/07/28 11:46:55 [main.go:189 func7()] [E] Controller emitted an error. Malformed version: (none)
2018/07/28 11:46:55 [I] interrupt
2018/07/28 11:46:55 [I] healthz listener closed
2018/07/28 11:46:55 [I] Scheduler shutting down
2018/07/28 11:46:55 [I] scheduler Shutdown complete.
2018/07/28 11:46:55 [main.go:151 func1()] [E] Disconnected from remote server.
2018/07/28 11:46:55 [I] accept tcp 127.0.0.1:7180: use of closed network connection

Can the raintank-probe run in Raspbian?

Thank you

**Comment by woodsaj** [comment]
yes, it should work on raspbian.  but it looks like the binary has not been built properly.
The main.GITHASH needs to be set when building.  see https://github.com/raintank/raintank-probe/blob/master/scripts/build.sh
