### ISSUE TITLE
some endpoints show no data for days

### ISSUE THREAD

**Issue by ganstawrap** [raintank/raintank-probe#58]
I'm using a private probe to monitor internal network and noticed some of the endpoints are now showing 'no data' on ping checks since 3 days ago. No change was made to the private probe or worldPing plugin for Grafana, and the following logs have been observed for raintank-probe:

raintank-probe[13281]: </html>
raintank-probe[13281]: will try again in 100ms (this attempt took 244.418628ms)
raintank-probe[13281]: 2018/08/13 19:58:09 [W] GrafanaNet failed to submit metrics: http 
raintank-probe[13281]: <head><title>400 Bad Request</title></head>
raintank-probe[13281]: <body bgcolor="white">
raintank-probe[13281]: <center><h1>400 Bad Request</h1></center>
raintank-probe[13281]: <hr><center>nginx/1.13.7</center>
raintank-probe[13281]: </body>
raintank-probe[13281]: </html>

Grafana is running on v5.2.1 and worldPing on v1.2.4.

**Comment by woodsaj** [comment]
This issue was resolved.

The problem was due to a corrupt DB entry leading to the backend believing there were multiple probes for the same location running.  When there are multiple probe instances for a location, each instance gets a portion of the checks.

**Comment by lantier** [comment]
I had this problem for a time now. The exactly problem
Any tips?
I didn't understand if it's a GrafanaNetDB thing or my Grafana DB
